### PR TITLE
Pillar Editor - Save file with extension, class comments, export removed from menu (but code still exists)

### PR DESCRIPTION
**Pull request by LaurineDargaud**
It uses 'book' archetype.
Pillar Editor asks user to give a pillar directory which becomes the reference to copy data for building.

### CODE REVIEW

**Comment by Ducasse** [comment]
We will have to pay attention about removing files. So I prefer to take the time to review it carefully.

**Comment by Ducasse** [comment]
After thinking about it we are thinking that it would be simpler and more modular that the export just export the pillar or microdown file. And then we guy that move it or not in his project. 
Would this solution work for you?

**Comment by LaurineDargaud** [comment]
I removed export. We can open and save text files through my Pillar Editor, and extension is pre-written in save window.

**Comment by Ducasse** [comment]
Super!

**Pull request merged**
