### PR TITLE
392-Baseline-of-Pillar-Core-does-not-load-Pillar-Core

### LINKED ISSUE #392: Baseline of Pillar Core does not load Pillar-Core
The Package `Pillar-Core` is not loaded by `BaselineOfPillarCore`.

### PR DESCRIPTION
**Pull request by kasperosterbye**
Fixes #392

Added package instruction to 'BaselineOfPillarCore' to load 'Pillar-Core'.

### CODE REVIEW

**Comment by kasperosterbye** [comment]
This one is a showstopper to me. 
It seems the checks that failed are all in some older versions, and I am not sure it is I who did anything wrong.

**Comment by Ducasse** [comment]
Hi kasper 
I'm on vacation and I will try to check but I have some important stuff to do. 
I merged it because this is strange. I think that PillarCore never worked in fact.

**Comment by kasperosterbye** [comment]
Thanks Stef. Enjoy your vacation.

**Comment by Ducasse** [comment]
Thanks. I have doctor visits and painting fences :)

**Pull request merged**
