### PR TITLE
389-PRVisitor-and-Model-classes-should-not-return-self

### LINKED ISSUE #389: PRVisitor and Model classes should not return self
PRVisitor is build for steaming, not for aggregation, but could do both.
All `visitXXX:` and all `accept:` methods should return the result of accept/visit rather than `self`.

### PR DESCRIPTION
**Pull request by kasperosterbye**
Fixes #389

Added return in all (I hope) accept: methods in the model, and visitXXX: methods of PRVisitor

### CODE REVIEW

**Comment by Ducasse** [comment]
I will have to have a look at the travis builds. Anyway. I have a question why do you need returning values, in general we accumulated in an internal stream. 
(now returning values do not block internal accumulation). :)

**Comment by Ducasse** [comment]
I have the impression that your PR removed all the extensions 

 src/Pillar-Model/PRVisitor.extension.st

Can you check?

**Comment by kasperosterbye** [comment]
There is a git thingie which has been bugging me. I will redo it. and close this PR.
I expect to make a new one soon.

With respect to streaming vs. synthesis. Consider this pillar:

`!Pharo is ""really ''cool''""`

To produce that `cool` it need to be put in bold, italics and a large font. Using synthesis those attributes are simply added on their way up the document tree. Using streaming I would need a brush decorator pattern to be able to write each character with more than one brush (or some other idea I did not see).

While this can be done, the code is much simpler using synthesis, having no need for canvas, nor brushes. I was just trying to keep it simple.

**Comment by guillep** [comment]
Yes, I'd seen some complications like that with the templated writer. The templated writer should check if there is a template for a given node (let's say bold) and if not delegate it to a default writer, which should recurse in the templated writer again...

I followed blindly how pillar was done at the time to keep the existing structure. I'd like to see how that's simplified using this pattern :)

**Comment by kasperosterbye** [comment]
I am not quite ready to release the rich text composer. But so far is is just one subclass of PRVisitor.

The following methods gives you the gist of it:

```Smalltalk
visitBoldFormat: anObject
	^ (self visitFormat: anObject) addAttribute: TextEmphasis bold

visitHeader: aHeader
	| header |
	header := self visitDocumentGroup: aHeader.
	header addAttribute: (self headerLevelFont: aHeader level).
	^  header, Character cr asText

visitText: anObject
	^ anObject text asText addAttribute: (TextIndent tabs: nesting)
```

Still looking for a way to do tables... 🤔

**Pull request closed without merging**
