### PR TITLE
389-PRVisitor-and-Model-classes-should-not-return-self

### LINKED ISSUE #389: PRVisitor and Model classes should not return self
PRVisitor is build for steaming, not for aggregation, but could do both.
All `visitXXX:` and all `accept:` methods should return the result of accept/visit rather than `self`.

### PR DESCRIPTION
**Pull request by kasperosterbye**
Fixes #389 - adds return visitors and accept

I hope this one is better. I would like to learn how to run all the tests locally, but so many new things yet to pick-up.

Done using this rewrite script:
```Smalltalk
(PRVisitor methodDict keys select: [ :sel | sel beginsWith: 'visit'])
do: [ :sel | 
	|source cat|
	source := (PRVisitor >> sel) sourceCode copyReplaceAll: '	self' with: '	^ self'.
	cat := (PRVisitor >> sel) protocol asString.
	PRVisitor compile: source classified: cat.
	].

((PRDocumentItem allSubclasses ,{PRDocumentItem}) select: [:cl | cl includesSelector:  #accept:]) 
do: [ :docClass | 
	|source cat|
	source := (docClass >> #accept:) sourceCode copyReplaceAll: '	aVisitor' with: '	^ aVisitor'.
	cat := (docClass >> #accept:) protocol asString.
	docClass compile: source classified: cat.
	].
```

and added return to the `start:`method in `PRVisitor` by hand.

### CODE REVIEW

**Comment by guillep** [comment]
Hi @kasperosterbye , there are two sets of tests: unit tests and integration tests (the ones in package `Pillar-Tests-Integration`).
Integration tests are pretty heavy to be run on every change (they launch pdf compilation through latex...).

If you open the test runner and filter packages starting with Pillar select all packages and deselect `Pillar-Tests-Integration`. It should take a couple of seconds.

**Comment by kasperosterbye** [comment]
I give up. I have no clue as to what goes wrong.
If I apply the in-image tests they come out all green.

**Comment by guillep** [comment]
Looking at the output in here

https://travis-ci.org/pillar-markup/pillar/builds/591349010?utm_source=github_status&utm_medium=notification

Most of them are green, still I'd say that the failing jobs seem not related with your changes.
Most of the failing jobs are related to ssh connectivity errors.

So I'd say this is good to integrate. @Ducasse ?

**Comment by Ducasse** [comment]
oops I do not get email on this repo so I just saw this by accident. 
Yes it was on my to do to get all tests green. But I got sucked in another task.

**Pull request merged**
