### PR TITLE
Use Petit parser 2 instead of Petit parser 1

### PR DESCRIPTION
**Pull request by JurajKubelka**
This pull request introduce:

- Pillar grammar and parser inherits from Petit parser two
- Original Pillar grammar based on Petit parser one is in '*Old' package
- Most of Pillar nodes has proper start and stop values
- Add two parsing annotation strategies: one that raises an error when annotation name is not unknown; another, that creates a `PRUndefinedAnnotation` node (useful for text highlighting)
- Add Annotation parameters as AST nodes (useful for editing and text highlighting) 
- Add back support for `${annotation:value}$` and `${annotation:key=value}$`

### CODE REVIEW

**Comment by JurajKubelka** [comment]
Hi @guillep and @Ducasse! 

Is there any change to integrate this PR? I introduced several changes and I do not want to be out of sync with you.

**Comment by Ducasse** [comment]
I will come but we were super busy and travelling around.

**Comment by guillep** [comment]
Well, the unit tests are still broken. Are they all running green on your machine (try running all but the IntegrationTests package).

Then, I'll make a tag before this is integrated so we can identify versions.

**Comment by JurajKubelka** [comment]
I have issue with those test cases:

screen shot 2018-06-30 at 14 38 46

I have an impression that it is not related to my changes. I have not tested if all tests are green at the beginning of my work. The errors are like this: 

screen shot 2018-06-30 at 14 40 40

Should I fix it? Can you give me some insights why it fails? I do not understand those test cases.

**Comment by JurajKubelka** [comment]
I think, Appveyor CI failures are not PR related.
And notice that `dev-7` is neither green (https://travis-ci.org/pillar-markup/pillar/builds/397031122).

**Comment by JurajKubelka** [comment]
@Ducasse: It is fine, I just asked. Look at it when you have time :-)

**Comment by JurajKubelka** [comment]
Hi @guillep and @Ducasse,

the last changes add back the support for `${annotation:value}$` and `${annotation:key=value}$`. I hope you like it :-)

**Comment by StephaneDucasse** [comment]
Hi juraj

in fact we deprecated annotation:value and we wanted to force annotation:key=value
We migrated all the books using Pillar 70 to be updated. 
Now we did that because it was too painful to learn petit parser and modify it. 
Do you use the parametersFrom: method we added because we do not want to get 
'11' or 'true' but 11 and true as parameter value (because else we have to check strings!!!!) and this was a bad idea of the previous design choice. 
So I'm ok with your change if it use the code validation we developed.

**Comment by JurajKubelka** [comment]
Hi @StephaneDucasse,

yes, I follow the latest changes in `dev-7` and it returns numbers, booleans, etc. I also simplified the code and deprecated some methods, e.g., `adaptKeysOn:`, `checkKeysOf:`

**Comment by StephaneDucasse** [comment]
Ok then this is cool.

**Comment by QDucasse** [comment]
Juraj (this is stef :)
Are we clear that in ${annotation:value}$, the value of key is value?
and that ${annotation:value|key2}$ and key2=true?
Then ${annotation:key}$ should not work.
Finally sometimes we do not want people to be able to not specify a value for example
${showMethod:class=Array  class|selector=new:}$

**Comment by JurajKubelka** [comment]
Hi @QDucasse 

> Are we clear that in ${annotation:value}$, the value of key is value?

The current logic for `${annotation:foo}$` is the following:
- `foo=true` if `possibleParameters` includes the `foo` keyword
- `bar=foo` if `possibleParameters`does NOT  includes the `foo` keyword, and the first possible parameter is `bar`

This logic apply only for the first parameter that can be defined with or without the `key` name. This is the most concise logic I figured out. Notice that writing `${annotation:value|key2}$` and `${annotation:key2}$` will end up with the same parameter `key2=true`.

> and that ${annotation:value|key2}$ and key2=true?

yes.

> Then ${annotation:key}$ should not work.

It works (`key=true`) as I explain above. And I believe that it is coherent solution as the `key` might have boolean values. You can then write `${annotation:key1|key2}$` where `key1=true` and `key2=true`.

> Finally sometimes we do not want people to be able to not specify a value for example
${showMethod:class=Array class|selector=new:}$

I am not sure about it. We can add property like `Annotation class >> #isParameterWithoutKeyEnabled`. I am not sure if it is really necessary. 

What do you think?

**Comment by JurajKubelka** [comment]
Hi @QDucasse, @Ducasse, @guillep,

I prefer to keep the discussion about the PR here. So the raised question is:

> did you check why your PR is breaking our tests?

Can you please explain how do you test it? 

I do using `dev-7`: 

```Smalltalk
Metacello new
   baseline: 'Pillar';
   repository: 'github://pillar-markup/pillar:dev-7/src';
   load.
```

And I have: 

screen shot 2018-08-01 at 09 28 39

I do using `dev-petitparser2`(the PR's source code): 

```Smalltalk
Metacello new
   baseline: 'Pillar';
   repository: 'github://feenkcom/pillar:dev-petitparser2/src';
   load.
```

And I have

screen shot 2018-08-01 at 09 28 45

As you can see in both cases the failing tests are the same. I think those tests have nothing to do with the PR and I quite do not understand how to fix them (their meaning). 


Both builds are done in Pharo 7:

```
Pharo 7.0
Build information: Pharo-7.0+alpha.build.1150.sha.38a61333933eb2e29c5f01c73a875cdcda3a1bb3 (64 Bit)
```

[Travis PR](https://travis-ci.org/pillar-markup/pillar/builds/399759665?utm_source=github_status&utm_medium=notification) is quite green. Checking [Travis dev-7](https://travis-ci.org/pillar-markup/pillar/builds/407170192) there are the same issues. The failing test does not seam to have relation with the PR. Sometimes it looks like an internet issue. Maybe the Travis configuration is broken in such cases? 

Currently, there is a merge conflict as someone has been working on the same source code part (annotation). If you think that it is time to approve the PR, I will resolve the merge conflicts.

**Comment by JurajKubelka** [comment]
I fixed the merge conflict. I hope this will be integrated soon as @samakhov (and maybe someone else) touches the same source code from time to time.

**Comment by guillep** [comment]
Hi @JurajKubelka we are integrating it.
- We have created a new v7.1.0 tag with all changes that predate this one.
- We are relaunching the jobs to ensure they are green
- As soon as we integrate we will create v7.2.0 with the changes in the parser

**Pull request merged**
