### PR TITLE
simplify-conditionals

### PR DESCRIPTION
**Pull request by jecisc**
I'm trying a script to simplify conditionals related to nil and empty. 
Here is a PR with some cleanings for Pillar.

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks cyril. If it working in P8 because pillar is only P8 right now.

**Comment by Ducasse** [comment]
It looks like it is working
Now I do not understand why these tests are not passing anymore. 

#########################
4364# 2 tests did not pass: #

4367PRShowClassTransformerTest
4368 ✗ #testTransformerCreatesClassDefinitionCodeblock (409ms)
4394 ✗ #testTransformerCreatesClassDefinitionForUnknownClass (274ms)

May be we have some instability with the build on travis. I cannot check now since I must finish the iceberg chapters.

**Comment by jecisc** [comment]
@Ducasse It's now fixes

**Comment by jecisc** [comment]
Ping. 

J'aimerais fair d'autres PRs mais elles rentreraient en conflit avec celle ci

**Comment by Ducasse** [comment]
Oui merci cyril je suis a fond dans le parseur markdown. 
Je regarde

**Comment by Ducasse** [comment]
Je regarde presque tous les changements et j'ai appris des trucs donc c'est cool. 
Par contre je ne comprends pas

```
PRHTMLWriter >> noteAtEnd [
 	self noteDictionary isNotEmpty
 		ifTrue: [ canvas newLine.
                           canvas tag
 				name: 'hr';
 				with: ''. ]

 	self noteDictionary
 		ifNotEmpty: [ canvas newLine.
 			canvas tag
 				name: 'hr';
 				with: ''. ]
```

**Comment by jecisc** [comment]
#ifNotEmpty: is easier to read than `isNotEmpty ifTrue:`.

On top of that, #ifNotEmpty: can provide the collection as a parameter. In this case, this is useless, but in a lot of cases, it avoids the need to declare a temporary when the collection is empty or it avoids the need to call once again another method to get the collection content.

**Pull request merged**
